-- Modified Villains table with additional attributes
CREATE TABLE IF NOT EXISTS "Villains" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- Primary key as BIGINT
    "Name" VARCHAR(255) NOT NULL,
    "Alias" VARCHAR(255),
    "PowerLevel" INT NOT NULL,                 -- Villain's power level
    "Origin" VARCHAR(255),                     -- Origin location or planet
    "Motive" TEXT,                             -- Villain's primary motive or objective
    "FirstAppearance" DATE,                    -- Date of the first appearance
    "Nemesis" VARCHAR(255)                     -- Hero or main opponent
);

-- Modified Superpowers table with VillainId as BIGINT
CREATE TABLE IF NOT EXISTS "Superpowers" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,   -- Primary key as BIGINT
    "Name" VARCHAR(255) NOT NULL,
    "PowerLevel" INT NOT NULL,
    "Description" TEXT,
    "VillainId" BIGINT NOT NULL,                               -- Foreign key as BIGINT

    CONSTRAINT FK_Superpowers_Villain FOREIGN KEY ("VillainId") REFERENCES "Villains"("Id")
);

-- Insert Villains with additional attributes
INSERT INTO "Villains" ("Name", "Alias", "PowerLevel", "Origin", "Motive", "FirstAppearance", "Nemesis")
VALUES 
('Lex Luthor', 'Lex', 90, 'Metropolis', 'Destruction of Superman', '1940-04-01', 'Superman'),
('Joker', 'The Clown Prince of Crime', 85, 'Gotham City', 'Chaos and Anarchy', '1940-04-25', 'Batman'),
('Cheetah', 'Barbara Minerva', 80, 'Unknown', 'Revenge on Wonder Woman', '1943-10-01', 'Wonder Woman'),
('Darkseid', 'Lord of Apokolips', 100, 'Apokolips', 'Control of the universe', '1970-02-01', 'Justice League'),
('Sinestro', 'Master of Fear', 88, 'Korugar', 'Universal domination', '1961-08-01', 'Green Lantern'),
('Deathstroke', 'Slade Wilson', 85, 'Earth', 'Assassination and personal vendettas', '1980-12-01', 'Teen Titans'),
('Black Adam', 'Teth-Adam', 95, 'Kahndaq', 'Protect Kahndaq and destroy enemies', '1945-12-01', 'Shazam'),
('Bizarro', 'Mirror Superman', 70, 'Bizarro World', 'Be like Superman', '1958-10-01', 'Superman'),
('Brainiac', 'The Collector of Worlds', 95, 'Colu', 'Collect and control knowledge', '1958-07-01', 'Superman'),
('Reverse-Flash', 'Eobard Thawne', 95, 'Future', 'Destroy the Flash', '1963-09-01', 'The Flash');

-- Insert Superpowers with VillainId as BIGINT references
INSERT INTO "Superpowers" ("Name", "PowerLevel", "Description", "VillainId")
VALUES 
('Genius-Level Intellect', 100, 'Expert strategist and scientist', 1),  -- Lex Luthor
('Insanity', 95, 'Unpredictable, dangerous, and deranged mind', 2),    -- Joker
('Superhuman Strength', 90, 'Enhanced physical strength and speed', 3), -- Cheetah
('Omega Beams', 98, 'Destructive energy beams from eyes', 4),          -- Darkseid
('Fear Manipulation', 95, 'Instills intense fear in others', 5),       -- Sinestro
('Master Assassin', 85, 'Highly trained in combat and assassination', 6), -- Deathstroke
('Divine Power', 99, 'God-like abilities from Egyptian gods', 7),      -- Black Adam
('Bizarro Vision', 80, 'Opposite version of Superman’s powers', 8),    -- Bizarro
('Knowledge Absorption', 92, 'Gains intelligence by absorbing data', 9), -- Brainiac
('Speed Force Manipulation', 97, 'Access to Speed Force powers', 10);  -- Reverse-Flash
